import WalletProvider from '@ai-rsc/providers/WalletProvider';
import { TooltipProvider } from '@radix-ui/react-tooltip';
import '@rainbow-me/rainbowkit/styles.css';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Open_Sans } from 'next/font/google';
import { AI } from './actions';
import './globals.css';

//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AI>
      <html lang="en">
        <body className={openSans.className}>
          <ThemeProvider>
            <TooltipProvider>
              <WalletProvider>{children}</WalletProvider>
            </TooltipProvider>
          </ThemeProvider>
        </body>
      </html>
    </AI>
  );
}
